import tests.items.test_anti
import tests.items.test_anti_king
import tests.items.test_anti_knight
import tests.items.test_anti_monkey
import tests.items.test_anti_queen
import tests.items.test_arrow
import tests.items.test_between
import tests.items.test_board
import tests.items.test_box_item
import tests.items.test_cell
import tests.items.test_column
import tests.items.test_column_indexer
import tests.items.test_composed
import tests.items.test_diagonals
import tests.items.test_difference_pair
import tests.items.test_disjoint_group
import tests.items.test_dutch_whisper
import tests.items.test_entropic
import tests.items.test_equal_sum
import tests.items.test_frame
import tests.items.test_german_whisper
import tests.items.test_greater_than_equal_difference_pair
import tests.items.test_indexing
import tests.items.test_item
import tests.items.test_knowns
import tests.items.test_kropki_pair
import tests.items.test_less_than_equal_difference_line
import tests.items.test_less_than_equal_difference_pair
import tests.items.test_line
import tests.items.test_little_killer
import tests.items.test_lock_out
import tests.items.test_magic_square
import tests.items.test_pair
import tests.items.test_palindrome
import tests.items.test_quadruple
import tests.items.test_region
import tests.items.test_region_sets
import tests.items.test_renban
import tests.items.test_row
import tests.items.test_row_indexer
import tests.items.test_solution
import tests.items.test_thermometer
import tests.items.test_v_pair
import tests.items.test_vi_pair
import tests.items.test_window
import tests.items.test_x_pair
import tests.items.test_xi_pair
