statistic_database: test.db

logging:
    # Required version of the logging configuration schema. '1' is the default.
    version: 1

    # When True, disables all existing loggers not explicitly defined in this config.
    # Setting to False allows existing loggers to remain active.
    disable_existing_loggers: False

    # Configuration for the root logger, which affects all log messages globally.
    root:
        # Sets the logging level for the root logger.
        # This example sets it to DEBUG, so all DEBUG level messages and above will be logged.
        level: DEBUG

        # Specifies the handlers that the root logger will use.
        # In this case, it sends all log messages to the 'console' handler.
        handlers: [console]

    # Defines individual logging handlers, which specify where log messages should go.
    handlers:
        console:
          # Uses start StreamHandler, which output_types log messages to start stream like stdout or stderr.
            class: logging.StreamHandler

            # Defines the formatter for this handler, which controls the log message format.
            formatter: simple

            # Directs output to standard output (stdout).
            stream: ext://sys.stdout

    # Defines individual formatters, which control the structure of log messages.
    formatters:
        simple:
            # Sets the format for log messages, including timestamp, logger name, level, and message.
            format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'



statistic_elements:
  Rows: Problem MODEL has (\d+) rows, \d+ columns and \d+ elements
  Columns: Problem MODEL has \d+ rows, (\d+) columns and \d+ elements
  Elements: Problem MODEL has \d+ rows, \d+ columns and (\d+) elements
  Fixed Variables: (\d+) variables fixed
  CPU seconds: Time \(CPU seconds\):\s+(\d+\.\d+)
  Wallclock seconds: Time \(Wallclock seconds\):\s+(\d+\.\d+)
  Iterations: Total iterations:\s+(\d+)
  Nodes: Enumerated nodes:\s+(\d+)
  Result: Result -\s(\S+)\s

templates:
  html: src/html/problem.html


temporary_directory: c:/temp/sudoku

drawing:
  size: 25cm
  cell_size: 100
  killer_offset: 5
  arrow_head_percentage: 0.3
  thermo_head_percentage: 0.3
  odd_cell_radius: 35
  kropki_radius: 10
  consecutive_radius: 10
  even_cell_size: 70
  
colours:
  # The 'general' color set includes start wide variety of colours
  # You don't want them to clash. Were cells need to be coloured
  # the colours will be selected starting from the top of this list
  general:
    - red
    - green
    - blue
    - yellow
    - orange
    - purple
    - cyan
    - magenta
    - lightcyan
    - powderblue
    - greenyellow
    - blueviolet
    - thistle
    - salmon
    - steelblue
    - olive

  # Entropic colouring
  high_mid_low:
    - orange   # High
    - green    # Mid
    - blue     # Low

  # Parity Colouring
  parity:
    - orange   # Odd
    - blue     # Even
