"""Module that handles constraints."""

import src.items.anti
import src.items.anti_bltr
import src.items.anti_diagonal
import src.items.anti_king
import src.items.anti_knight
import src.items.anti_monkey
import src.items.anti_queens
import src.items.anti_tlbr
import src.items.asterix
import src.items.battenburg
import src.items.between_line
import src.items.bltr
import src.items.board
import src.items.box
import src.items.boxes
import src.items.cell
import src.items.cell_reference
import src.items.center_product
import src.items.cloned_region
import src.items.column
import src.items.column_indexer
import src.items.columns
import src.items.composed_item
import src.items.consecutive_pair
import src.items.constraint_exception
import src.items.constraints
import src.items.diagonals
import src.items.difference_line
import src.items.difference_pair
import src.items.disjoint_group
import src.items.disjoint_groups
import src.items.distinct_renban_line
import src.items.dutch_whisper_line
import src.items.entropic_line
import src.items.equal_sum_line
import src.items.even_cell
import src.items.exclusion
import src.items.first_n
import src.items.fixed_product_pair
import src.items.fixed_ratio_pair
import src.items.fixed_sum_pair
import src.items.fortress_cell
import src.items.frame
import src.items.frame_product
import src.items.frozen_thermometer_line
import src.items.german_whisper_line
import src.items.girandola
import src.items.greater_than_equal_difference_line
import src.items.greater_than_equal_difference_pair
import src.items.greater_than_pair
import src.items.high_cell
import src.items.indexing
import src.items.item
import src.items.killer
import src.items.knight
import src.items.known_cell
import src.items.known
import src.items.kropki_pair
import src.items.less_than_equal_difference_line
import src.items.less_than_equal_difference_pair
import src.items.line
import src.items.little_killer
import src.items.lock_out_line
import src.items.low_cell
import src.items.magic_square
import src.items.max_arrow
import src.items.mid_cell
import src.items.min_max_difference
import src.items.min_max_sum
import src.items.mountain_line
import src.items.numbered_room
import src.items.odd_cell
import src.items.orthogonal_product
import src.items.orthogonally_adjacent
import src.items.outside
import src.items.pair
import src.items.palindrome_line
import src.items.pencil_mark
import src.items.product
import src.items.product_arrow
import src.items.quadro
import src.items.quadruple
import src.items.region
import src.items.region_set
import src.items.renban_line
import src.items.rossini
import src.items.row
import src.items.row_indexer
import src.items.rows
import src.items.sandwich
import src.items.sequence_line
import src.items.simple_thermometer_line
import src.items.solution
import src.items.standard_diagonal
import src.items.standard_region
import src.items.standard_region_set
import src.items.sum_arrow_line
import src.items.thermometer_line
import src.items.tlbr
import src.items.tlbr_refecting_diagonal
import src.items.unique_region
import src.items.v_pair
import src.items.variable_difference_pair
import src.items.variable_pair
import src.items.variable_product_pair
import src.items.variable_ratio_pair
import src.items.variable_sum_pair
import src.items.vi_pair
import src.items.window
import src.items.x_pair
import src.items.xi_pair

# pylint: disable=W0107
pass
