"""Module that handles constraints."""

import src.items.anti
import src.items.anti_king
import src.items.anti_knight
import src.items.anti_monkey
import src.items.anti_queen
import src.items.arrow
import src.items.asterix
import src.items.between
import src.items.bltr
import src.items.board
import src.items.box
import src.items.boxes
import src.items.cell
import src.items.cell_reference
import src.items.column
import src.items.column_indexer
import src.items.columns
import src.items.composed
import src.items.consecutive_pair
import src.items.constraint_exception
import src.items.constraints
import src.items.diagonals
import src.items.difference_line
import src.items.difference_pair
import src.items.different_pair
import src.items.disjoint_group
import src.items.disjoint_groups
import src.items.distinct_renban
import src.items.dutch_whisper
import src.items.entropic
import src.items.equal_sum
import src.items.even_cell
import src.items.first_n
import src.items.fortress_cell
import src.items.frame
import src.items.frozen_thermometer
import src.items.german_whisper
import src.items.greater_than_equal_difference_line
import src.items.greater_than_equal_difference_pair
import src.items.greater_than_pair
import src.items.indexing
import src.items.item
import src.items.knight
import src.items.known_cell
import src.items.knowns
import src.items.kropki_pair
import src.items.less_than_equal_difference_line
import src.items.less_than_equal_difference_pair
import src.items.line
import src.items.little_killer
import src.items.lock_out
import src.items.magic_square
import src.items.odd_cell
import src.items.outside
import src.items.pair
import src.items.palindrome
import src.items.quadruple
import src.items.region
import src.items.region_sets
import src.items.renban
import src.items.rossini
import src.items.row
import src.items.row_indexer
import src.items.rows
import src.items.simple_thermometer
import src.items.solution
import src.items.standard_region
import src.items.sum_pair
import src.items.thermometer
import src.items.tlbr
import src.items.v_pair
import src.items.vi_pair
import src.items.window
import src.items.x_pair
import src.items.xi_pair

pass
