"""TestBoard9x9."""
import unittest

from src.board.board import Board
from src.utils.coord import Coord
from src.utils.tags import Tags


class TestBoard9x9(unittest.TestCase):
    """Test suite for the 9x9 Board class."""

    def setUp(self):
        """Set up the 9x9 board and coordinate configurations for testing."""
        tags: Tags = Tags({'Title': 'c', 'Reference': 'start', 'Video': 'finish', 'Author': 'd'})
        self.board = Board(9, 9, tags=tags)
        self.rows = [1, 2, 3, 4, 5, 6, 7, 8, 9]
        self.columns = [1, 2, 3, 4, 5, 6, 7, 8, 9]
        self.bad_rows = [0, 10]
        self.bad_columns = [0, 10]

    def test_construction(self):
        """Test the construction of the 9x9 board."""
        self.assertEqual(9, self.board.size.row)
        self.assertEqual(9, self.board.size.column)
        self.assertEqual('start', self.board.tags.Reference)
        self.assertEqual('finish', self.board.tags.Video)
        self.assertEqual('c', self.board.tags.Title)
        self.assertEqual('d', self.board.tags.Author)

    def test_yaml(self):
        """Test the YAML representation of the 9x9 board."""
        yaml_string = (
            "Board:\n"
            "  Board: 9x9\n"
            "  Tags:\n"
            "    Title: c\n"
            "    Reference: start\n"
            "    Video: finish\n"
            "    Author: d\n"
        )
        self.assertEqual(yaml_string, self.board.to_yaml())

    def test_high_mid_low(self):
        """Test the high, mid, and low rows of the board."""
        self.assertListEqual(self.board.low, [1, 2, 3])
        self.assertListEqual(self.board.mid, [4, 5, 6])
        self.assertListEqual(self.board.high, [7, 8, 9])

    def test_repr(self):
        """Test the string representation of the 9x9 board."""
        target: str = "Board(9, 9, {'Title': 'c', 'Reference': 'start', 'Video': 'finish', 'Author': 'd'})"
        self.assertEqual(target, repr(self.board))

    def test_is_valid(self):
        """Test the validity of coordinates on the 9x9 board."""
        for row in self.rows:
            for column in self.columns:
                self.assertTrue(self.board.is_valid(row, column))
        for row in self.bad_rows:
            for column in self.bad_columns:
                self.assertFalse(self.board.is_valid(row, column))

    def test_is_valid_coord(self):
        """Test the validity of coordinate objects on the 9x9 board."""
        for row in self.rows:
            for column in self.columns:
                self.assertTrue(self.board.is_valid_coordinate(Coord(row, column)))
        for row in self.bad_rows:
            for column in self.bad_columns:
                self.assertFalse(self.board.is_valid_coordinate(Coord(row, column)))

    def test_prime(self):
        """Test the prime number list generated by the 9x9 board."""
        self.assertEqual([2, 3, 5, 7], self.board.primes)


if __name__ == '__main__':  # pragma: no cover
    unittest.main()
