import src.parsers.cell_list_parser
import src.parsers.cell_pairs_parser
import src.parsers.cell_parser
import src.parsers.cell_value_parser
import src.parsers.digit_parser
import src.parsers.digits_parser
import src.parsers.little_killers_parser
import src.parsers.mock_parser
import src.parsers.outside_arrow_value_parser
import src.parsers.parser
import src.parsers.quadruples_parser
import src.parsers.rossini_parser
import src.parsers.unknown_parser
import src.parsers.vertex_digit_parser
import src.parsers.vertex_value_parser
