class Config:
    CELL_SIZE = 100
    KILLER_OFFSET = 5
    ARROW_HEAD_PERCENTAGE = 0.3
    THERMO_HEAD_PERCENTAGE = 0.3
    ODD_CELL_RADIUS = 35
    KROPKI_RADIUS = 10
    CONSECUTIVE_RADIUS = 10
    EVEN_CELL_SIZE = 70
