import tests.utils.test_angle
import tests.utils.test_coord
import tests.utils.test_coord_list
import tests.utils.test_cyclic
import tests.utils.test_direction
import tests.utils.test_matrix
import tests.utils.test_order
import tests.utils.test_point
import tests.utils.test_side
import tests.utils.test_tag
import tests.utils.test_tag_list
import tests.utils.test_vector
import tests.utils.test_vector_list
